drop-settings:
  base-drop-chance: 0.5    # Tỉ lệ cơ bản để đào được NFT (5% = 5% cơ hội rơi)
  cooldown-seconds: 3       # Số giây cooldown giữa 2 lần mint NFT

rarity-drop-rates:
  common: 5.0               # Tỉ lệ rơi NFT Common
  uncommon: 2.0             # Tỉ lệ rơi NFT Uncommon
  rare: 1.0                 # Tỉ lệ rơi NFT Rare
  epic: 0.5                 # Tỉ lệ rơi NFT Epic
  legendary: 0.1            # Tỉ lệ rơi NFT Legendary
